### ISSUE TITLE
Issue with flit.ini and conda package versions

### ISSUE THREAD

**Issue by kikocorreoso** [takluyver/flonda#3]
Hi,

Maybe I'm doing it wrong.

This is my `flit.ini` file:

```
[metadata]
module=tutormagic
author=Kiko Correoso
author-email=kiko@example.noway
home-page=https://github.com/kikocorreoso/tutormagic
requires=notebook>=4.3.2
requires-python= >=2.7
description-file=README.rst
classifiers=Intended Audience :: Education
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 2
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.6
    Topic :: Text Processing :: Markup :: HTML
```

I have checked that [notebook version >= 4.3.2 is on conda-forge channel](https://anaconda.org/conda-forge/notebook/files). But when I try to install tutormagic (https://anaconda.org/kikocorreoso/tutormagic) using

` conda install -c kikocorreoso tutormagic`

it raises:

```
Fetching package metadata ...............
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - tutormagic -> notebook>=4.3

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/kikocorreoso/win-32
  - https://conda.anaconda.org/kikocorreoso/noarch
  - https://conda.anaconda.org/conda-forge/win-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/win-32
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-32
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-32
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-32
  - https://repo.continuum.io/pkgs/msys2/noarch
```

I know this is a [risky] package but I was testing it.

**Comment by takluyver** [comment]
I suspect conda is looking for a package called `'notebook>=4.3'`, rather than separating it into name and version specification. We'll need to work out how conda packages specify that info.

**Comment by takluyver** [comment]
Glancing at an example built the normal way, it looks like maybe it needs a space before the `>=`

**Comment by kikocorreoso** [comment]
It seems that with this line:

`requires=notebook >=4.3.2`

instead of:

`requires=notebook>=4.3.2`

works correctly.

Thanks for taking the time.

**Comment by takluyver** [comment]
Thanks for checking :-).

Requirements are the biggest kludge in doing this - the two package systems have different ways of specifying them, and different packages you can require. You can provide flonda with a totally separate list of conda requirements in the config file, but if you don't it will attempt to translate the PyPI requirements into conda requirements. That's what's going wrong here.

**Comment by kikocorreoso** [comment]
I know the task to be solved here is not an easy one...

Thanks for trying to make easier the python packaging ecosystem.

**Comment by takluyver** [comment]
Closing preparation for archiving this project - flonda is an idea that never took off, and I don't think I'm likely to return to it.
