### ISSUE TITLE
Maybe implement rule-based edits of the recipe

### ISSUE THREAD

**Issue by sgbaird** [takluyver/flonda#5]
Right now, my workflow involves using flit, grayskull, and conda-souschef to package via PyPI, create a skeleton for a conda recipe, and then tweak it programatically. https://github.com/marcelotrevisani/souschef/issues/32

Not sure if flonda could benefit from any of these approaches.

An example using GitHub actions is at https://github.com/sparks-baird/mat_discover/blob/main/.github/workflows/test-publish-release.yml

**Comment by takluyver** [comment]
Flonda is really an abandoned experiment at this point - I don't think anyone is using it. The idea was that it would be possible to create a subset of conda packages without going through a meta.yaml file and conda-build. This was before conda had noarch packages, and we were waiting hours for Mac builders to go through a massive queue of packages, most of them pure Python code where 'building' just meant stuffing the same files into a tarball in slightly different folder structures.

At least back then, there was no public documentation of the conda package format, so I was reverse engineering it. I never really managed to get anyone interested in the idea, and when noarch came along, it was much harder to justify bypassing conda's normal build pipeline.

(IIRC, conda actually had noarch packages early on, got rid of them, then reintroduced them. I was playing with flonda in the gap where it didn't support noarch.)

**Comment by sgbaird** [comment]
@takluyver that's good to know - and the history makes sense (both starting `flonda` and then abandoning it later). Thanks for clarifying this!
